
version: '3'
services:
    mysq:
        image: mysql:8.0.13
        restart: unless-stopped
        ports:
            - "192.168.99.100:3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Qwerty.1
            MYSQL_DATABASE: restusertemplate
    
    
    backend:
        image: userrest
        ports: 
            - "192.168.99.100:3000:3000"